name: OpenAPI Dependabot

on:
  schedule:
    - cron: "0 2 * * *"   # Daily at 02:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  update-openapi-specs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout api-specs repo
        uses: actions/checkout@v4

      - name: Checkout your personal ballerina-library
        uses: actions/checkout@v4
        with:
          repository: TharaniDJ/ballerina-library 
          path: ballerina-library

      - name: Set up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0 
        with:
          version: 2201.10.0

      - name: Run OpenAPI Dependabot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Use the exact case: Dependabot
          cd ballerina-library/Dependabot
          
          # This lists files so you can see repos.json in the logs if it fails
          ls -F
          
          bal run main.bal
          cd ../../
          chmod +x ./scripts/create-pr.sh
          ./scripts/create-pr.sh

      
